import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Next Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border border-white flex justify-center">
          <nav className="flex m-2">
            <Link
              href="/"
              className="p-2 bg-gray-600 rounded hover:bg-gray-400 mx-2"
            >
              Home
            </Link>
            <Link
              href="/posts"
              className="p-2 bg-red-500 rounded hover:bg-red-400 mx-2"
            >
              목록
            </Link>
          </nav>
        </header>
        <main>{children}</main>
        <footer className="border border-white flex justify-center">
          푸터
        </footer>
      </body>
    </html>
  )
}
